---
title: "如何学习数学？"
author: "Maverick McQuillan"
date: "2024-06-30"
categories: [Learning Method]

---

## 学习数学的几个准则
我现在面临考研数学专业的压力，同时还要去学习英语和政治。但是关键在于把我的两门专业课学好，一门是高等代数还有一门是数学分析。那怎么样学，或者学到什么程度才能叫把这两门数学课程学好呢？我觉得按照重要性，应该分为以下几个标准：

### 完成比完美重要
无论你用什么办法去学习数学，最重要的是要把数学书中的内容学完。但是不能说看完一遍讲课视频，我就相当于完成了数学课程的学习，而是至少要自己主动学习一遍（可以不包含课程的习题内容）。

### 费曼学习法
学习的方法必须要用费曼学习法，无论是你写文章把你学的内容讲一遍，还是口述给自己讲课，你必须要用费曼学习法学习一遍。即使你用费曼学习法学习一遍也要比光看书和看视频学习两遍效果要好的多，因为被动学习和主动学习的效果是差异很大的，这是我高中的血淋淋的教训。

### 回忆
学完一遍后，你应该合上书，思考这节课都学习了什么。这种回忆的过程哪怕说很不完美，你回忆的时候发现自己好像没学过这节课一样（如果用费曼学习法学习，这种情况不会发生），也有巨大的意义。因为当你开始回忆的时候，你大脑中的神经网络会让各个知识点的神经元进行关联，你将来对数学的理解会更加透彻。在费曼学习法的条件下，你本身记忆知识点就比较牢靠，再加上回忆让这些知识点链接起来，想想如果这样学习，你还怕考不上研究生，考不上好大学吗？

### 重复
费曼学习法和回忆法都是加快你的学习效率的，但是如果没有大量的学习时间，你还是掌握不了数学的内容。那大量的学习时间主要在干什么？就是要尽可能的重复，当你学第二遍、第三遍（我认为超过第三遍的边际效用就很低了）时，你对你学习的数学书的内容整体的感知又会上升一大截，甚至你觉得你学习的不仅仅是数学而是上升到了哲学的境界。

## 具体的实际操作
就拿我现在学习的数学分析和高等数学进行举例，我该如何学习这两本书呢？

### 课程内容
我认为每节课我要先看书给自己讲一遍（分部分讲解，而不是一口气讲完），然后去B站看陈纪修或者谢启鸿的视频（因为有些很重要你不能理解的提示书里没有，只有课堂上有），整体学完之后，这是对自己学习的一种补充。同时要提醒自己不要做习题，因为做习题的话会花费大量时间，我们学习准则的第一条就是要完成一本书的内容。

### 真题训练
为了兼顾考研的情况，当你把一本书学完之后，赶紧去找对应的专业课真题，因为起码这个时候你可以把试卷中的每道题都可以看懂了。每个真题都要对照答案做两遍，做完至少五年的真题，我想当你完成这步的时候，你再去考场上答题，就不会是炮灰，而是一名有潜力的参赛选手。

### 课程习题
当你完成了前两步之后，你需要去做习题了，考研大部分的题可能就出自于教材的习题之中，所以做教材上的题是很有必要的。但是最重要的内容仍然是教材中的定理，所以在你去做教材习题时，应该先去把教材的内容温习一遍，再去做题。而做题时，你应该做两遍，这样才算真正把习题的熟练度提升。

### 书籍复习
当你把习题完成之后，你应该做的就是把整本书的内容再学习一遍，这是最终的结尾，经过这步，你对数学的了解可以说已经达到了一个境界，甚至你这辈子都不会忘记你所学习的内容，最重要的是你通过不断地学习数学，已经完全理解了数学的思想，这才是对你影响最大的地方。

## 英文教材的不同
我在具体操作中的习题部分针对的是中文教材，因为我要考研嘛！但是如果你学习的是英文教材而且没有任何特别大的关于考试的压力的话，我建议你直接把书本中的课程内容学三遍就可以了，但是不要做练习题，因为那样的边际效应就很低了。
英文教材跟中国教材不同的一点是它把你当成一个刚毕业的初中生去教你，而不是把你认为是一个985大学的学习好的学生来教你，所以课程的内容即使你不去看视频也能学会。这也是我学习陈纪修的书比较痛苦的地方，有些地方我想不通，我认为书里应该把其中的来龙去脉讲出来，结果它没写，你只能去看B站的陈纪修的视频，这其实也影响我的学习效率。
